# Generated by Django 4.2.1 on 2023-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
